spring:
  h2:
    console:
      enabled: true # localhost:8080/h2-console

  graphql:
    graphiql:
      enabled: true # localhost:8080/graphiql
      schema:
        locations: classpath:graphql/**/
        fileExtensions: .graphqls, .gqls
      printer:
        enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:../test
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop # create and destroy at the end of session
    show-sql: true